require: rubocop-rails
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
  - bin/**/*
  - lib/**/*
  - db/schema.rb
  - db/migrate/*.rb
  - db/seeds.rb
  - db/seeds/**/*.rb
  - config/puma.rb
  - config/routes.rb
  - node_modules/**/*
  - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Metrics/MethodLength:
  Max: 125

Metrics/BlockLength:
  Max: 125

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 100

Style/GuardClause:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false  

Layout/TrailingWhitespace:
  Enabled: false  

Style/WhileUntilModifier:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false
  
Style/WhileUntilDo:
  Enabled: false 

Lint/MissingSuper:
  Enabled: false 

Lint/EmptyBlock:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Lint/AmbiguousOperator:  
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/OptionalBooleanParameter:  
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Style/FloatDivision:   
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Style/MultilineBlockChain:  
  Enabled: false

Style/BlockDelimiters:  
  Enabled: false

Style/GlobalStdStream:  
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Metrics/BlockNesting:
  Max: 6  

Rails/LexicallyScopedActionFilter:
  Enabled: false  

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Rails/FilePath:
  Enabled: false
 
Rails/Date: 
  Enabled: false

Rails/FindBy:
  Enabled: false

Naming/RescuedExceptionsVariableName: 
  Enabled: false 

Rails/DynamicFindBy:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
  - app/controllers/login_controller.rb
  - config/initializers/devise.rb

Naming/MemoizedInstanceVariableName:
  Enabled: false